#机器人的一些调试参数
robot_main:

  #机身零点偏执0.03效果最好
  #电机三种控制模式下的电机控制位置和速度比例系数
  motor_pos_K: [0.05,3.0]
  motor_vel_K: [0.001,3.0] #[0.001,3.0]  
  motor_tor_K: [0.001,3.0]
  #默认的最优化二次型权重
  quadprog_S: [50.0, 40.0, 20.0, 1.0, 2.0, 3.0]
  quadprog_W: [0.01, 0.01, 0.0001]
  #默认的摆动腿力控制比例微分系数
  swing_Kp: [300.0, 300.0, 500.0] #[300.0, 300.0, 500.0]
  swing_Kd: [1.0,1.0,1.0]
  #默认的机身力控制比例微分系数
  body_Kp: [800.0, 800.0, 400.0, 90.0, 90.0, 120.0] 
  body_Kd: [22.0,22.0,10.0,22.0,22.0,18.0]
  #轮滑支撑分支之间的力矩控制比例微分系数
  inside_Kp: [50.0, 50.0,  0.0] #[50.0, 50.0,  0.0]
  inside_Kd: [2.0,  2.0,   0.0] #[0.0, 0.0,  0.0]

  #机身位置和线速度卡尔曼滤波估计
  body_PV_estimation: [ 0.02,0.02, #0.02,0.02#IMU姿态模型预测位置和线速度的协方差
                        0.002,     #关节运动学模型预测足位置的协方差
                        0.001,0.1, #关节运动学观测机身位置和线速度的协方差
                        0.001]     #关节运动学观测机身高度的协方差
  
  #对角自适应足行步态的参数
  walk_trot_adapt:
    #机身力控制比例微分系数
    body_Kp: [800.0, 800.0, 400.0, 10.0, 10.0, 120.0]
    body_Kd: [40.0, 40.0, 20.0,  50.0, 50.0, 12.0]
    #运动规划最大加速度
    acc_max: [10.0,10.0,1.0,0.5,0.3,10.0]

  #对角自适应轮滑步态的参数
  skating_trot_adapt:
    #机身力控制比例微分系数
    body_Kp: [800.0, 800.0, 400.0, 90.0, 90.0, 120.0] 
    body_Kd: [20.0,  20.0,  10.0,  20.0, 20.0, 18.0]

  #同侧自适应轮滑步态的参数
  skating_pace_adapt:
    #机身力控制比例微分系数
    body_Kp: [800.0, 800.0, 300.0, 90.0,  100.0, 120.0]
    body_Kd: [40.0,  40.0,  20.0,  20.0,  40.0, 18.0]

    
